package com.suxuantech.erpsys.ui.adapter;

import com.chad.library.adapter.base.BaseQuickAdapter;
import com.chad.library.adapter.base.BaseViewHolder;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;

/**
 * ......................我佛慈悲....................
 * ......................_oo0oo_.....................
 * .....................o8888888o....................
 * .....................88" . "88....................
 * .....................(| -_- |)....................
 * .....................0\  =  /0....................
 * ...................___/`---'\___..................
 * ..................' \\|     |// '.................
 * ................./ \\|||  :  |||// \..............
 * .............../ _||||| -卍-|||||- \..............
 * ..............|   | \\\  -  /// |   |.............
 * ..............| \_|  ''\---/''  |_/ |.............
 * ..............\  .-\__  '-'  ___/-. /.............
 * ............___'. .'  /--.--\  `. .'___...........
 * .........."" '<  `.___\_<|>_/___.' >' ""..........
 * ........| | :  `- \`.;`\ _ /`;.`/ - ` : | |.......
 * ........\  \ `_.   \_ __\ /__ _/   .-` /  /.......
 * ....=====`-.____`.___ \_____/___.-`___.-'=====....
 * ......................`=---='.....................
 * ..................佛祖开光 ,永无BUG................
 *
 * @author Created by 李站旗 on 2018/4/28 0028 19:15 .
 * QQ:1032992210
 * E-mail:lizhanqihd@163.com
 * @Description:
 */
public class MapQuickAdapter<T >  extends BaseQuickAdapter<T, BaseViewHolder> {
   private Map<T,T> mapData;
   private  T t;
    public  MapQuickAdapter(int layoutResId, Map<T, T> maps ) {
        super(layoutResId);
        this.mapData=maps;
        t=t;
    //定义一个用来存放key列表
        Iterator<T> iter=maps.keySet().iterator();
        if (mData==null){
            mData=new ArrayList<>();
        }
        while(iter.hasNext()){
          mData  .add(iter.next());
        }
    }

    @Override
    final protected void convert(BaseViewHolder helper, T item) {
        convert (helper,getData().lastIndexOf(item),item,mapData.get(item));
    }

    protected void convert (BaseViewHolder helper,int posstion, T key ,T value ) {

    }

}
