package com.suxuantech.erpsys.dialog;

import android.content.Context;
import android.support.annotation.StringRes;

import com.bigkoo.pickerview.TimePickerView;
import com.suxuantech.erpsys.R;

import java.util.Calendar;

/**
 * ......................我佛慈悲....................
 * ......................_oo0oo_.....................
 * .....................o8888888o....................
 * .....................88" . "88....................
 * .....................(| -_- |)....................
 * .....................0\  =  /0....................
 * ...................___/`---'\___..................
 * ..................' \\|     |// '.................
 * ................./ \\|||  :  |||// \..............
 * .............../ _||||| -卍-|||||- \..............
 * ..............|   | \\\  -  /// |   |.............
 * ..............| \_|  ''\---/''  |_/ |.............
 * ..............\  .-\__  '-'  ___/-. /.............
 * ............___'. .'  /--.--\  `. .'___...........
 * .........."" '<  `.___\_<|>_/___.' >' ""..........
 * ........| | :  `- \`.;`\ _ /`;.`/ - ` : | |.......
 * ........\  \ `_.   \_ __\ /__ _/   .-` /  /.......
 * ....=====`-.____`.___ \_____/___.-`___.-'=====....
 * ......................`=---='.....................
 * ..................佛祖开光 ,永无BUG................
 *
 * @author Created by 李站旗 on 2017/11/23 0023 21:40 .
 *         QQ:1032992210
 *         E-mail:lizhanqihd@163.com
 * @Description: todo(用一句话描述该文件做什么)
 */

public class TimeDialog {
    private TimeDialog() {
        /* cannot be instantiated */
        throw new UnsupportedOperationException("cannot be instantiated");
    }

    /**
     * 日期选择框精确到天
     * @param context
     * @param stingTitle 标题
     * @param listener 监听  DateUtil.dateToString(date, DateUtil.DatePattern.ONLY_DAY);格式化得到字符串
     */
    public static  void showDateSelectDay(Context context, @StringRes int stingTitle, int color, TimePickerView.OnTimeSelectListener listener) {
//        DateUtil.dateToString(date, DateUtil.DatePattern.ONLY_DAY);
       //时间选择器
        //选中事件回调
//                DateUtil.dateToString()
//年月日时分秒 的显示与否，不设置则默认全部显示
        TimePickerView  timePickerView = new TimePickerView.Builder(context, listener) //年月日时分秒 的显示与否，不设置则默认全部显示
                .setTitleText(context.getString(stingTitle)).setLineSpacingMultiplier(4).setType(new boolean[]{true, true, true, false  , false, false})
                .setTitleColor(stingTitle).setTitleColor(context.getResources().getColor(color)).setTitleBgColor(context.getResources().getColor(R.color.white)).build();
        timePickerView.setDate(Calendar.getInstance());//注：根据需求来决定是否使用该方法（一般是精确到秒的情况），此项可以在弹出选择器的时候重新设置当前时间，避免在初始化之后由于时间已经设定，导致选中时间与当前时间不匹配的问题。
        timePickerView.show();
    }
}
