package com.suxuantech.erpsys.presenter.connector;

import com.suxuantech.erpsys.entity.SearchOrderEntity;
import com.suxuantech.erpsys.entity.SearchOrderInforEntity;
import com.yanzhenjie.nohttp.rest.Response;

import java.util.List;

/**
 * ......................我佛慈悲....................
 * ......................_oo0oo_.....................
 * .....................o8888888o....................
 * .....................88" . "88....................
 * .....................(| -_- |)....................
 * .....................0\  =  /0....................
 * ...................___/`---'\___..................
 * ..................' \\|     |// '.................
 * ................./ \\|||  :  |||// \..............
 * .............../ _||||| -卍-|||||- \..............
 * ..............|   | \\\  -  /// |   |.............
 * ..............| \_|  ''\---/''  |_/ |.............
 * ..............\  .-\__  '-'  ___/-. /.............
 * ............___'. .'  /--.--\  `. .'___...........
 * .........."" '<  `.___\_<|>_/___.' >' ""..........
 * ........| | :  `- \`.;`\ _ /`;.`/ - ` : | |.......
 * ........\  \ `_.   \_ __\ /__ _/   .-` /  /.......
 * ....=====`-.____`.___ \_____/___.-`___.-'=====....
 * ......................`=---='.....................
 * ..................佛祖开光 ,永无BUG................
 *
 * @author Created by 李站旗 on 2017/12/11 0011 10:14 .
 *         QQ:1032992210
 *         E-mail:lizhanqihd@163.com
 * @Description: 接口搜索订单和搜索历史
 */

public interface ISearchOrderPresenter {
    /**
     *
     * @param data 数据
     * @param isRefesh 是否是刷新
     * @param hasMore 是否还有更多
     */
    void searchSucceed(List<SearchOrderEntity.DataBean> data, boolean isRefesh, boolean hasMore);
    void searchSucceed (List<SearchOrderInforEntity.DataBean> data );
    /**
     * 搜索失败结果
     * @param response
     * @param pageIndex 多少页的失败
     */
    void searchFailed(Response<SearchOrderEntity> response, int pageIndex);
}
