package com.suxuantech.erpsys.utils

import com.suxuantech.erpsys.entity.CompanyDomainEntity
import com.suxuantech.erpsys.entity.PhotoSchemeSearchEntity
import com.suxuantech.erpsys.entity.SearchOptionPanelEntity

/**
 * ......................我佛慈悲....................
 * ......................_oo0oo_.....................
 * .....................o8888888o....................
 * .....................88" . "88....................
 * .....................(| -_- |)....................
 * .....................0\  =  /0....................
 * ...................___/`---'\___..................
 * ..................' \\|     |// '.................
 * ................./ \\|||  :  |||// \..............
 * .............../ _||||| -卍-|||||- \..............
 * ..............|   | \\\  -  /// |   |.............
 * ..............| \_|  ''\---/''  |_/ |.............
 * ..............\  .-\__  '-'  ___/-. /.............
 * ............___'. .'  /--.--\  `. .'___...........
 * .........."" '<  `.___\_<|>_/___.' >' ""..........
 * ........| | :  `- \`.;`\ _ /`;.`/ - ` : | |.......
 * ........\  \ `_.   \_ __\ /__ _/   .-` /  /.......
 * ....=====`-.____`.___ \_____/___.-`___.-'=====....
 * ......................`=---='.....................
 * ..................佛祖开光 ,永无BUG................
 * @author Created by 李站旗 on 2018/5/24 0024 21:43 .
 * QQ:1032992210
 *  E-mail:lizhanqihd@163.com
 * @Description: todo(用一句话描述该文件做什么)
 */
public fun group(al: List<PhotoSchemeSearchEntity.DataBean>): Map<String?, List<PhotoSchemeSearchEntity.DataBean>> {
    return al.groupBy(PhotoSchemeSearchEntity.DataBean::orderid)
}

public fun groupPhotoSchedule(al: List<PhotoSchemeSearchEntity.DataBean>): ArrayList<ArrayList<PhotoSchemeSearchEntity.DataBean>> {
    var asb: ArrayList<ArrayList<PhotoSchemeSearchEntity.DataBean>> = ArrayList<ArrayList<PhotoSchemeSearchEntity.DataBean>>()
    val groupBy = al.groupBy(PhotoSchemeSearchEntity.DataBean::orderid);
    groupBy.keys.forEach {
        val get = groupBy.get(it);
        val addAll = asb.add((get as java.util.ArrayList<PhotoSchemeSearchEntity.DataBean>?)!!)
    }
    return asb;
}
public fun groupOptionPanelSchedule(al: List<SearchOptionPanelEntity.DataBean>): ArrayList<ArrayList<SearchOptionPanelEntity.DataBean>> {
    var asb: ArrayList<ArrayList<SearchOptionPanelEntity.DataBean>> = ArrayList<ArrayList<SearchOptionPanelEntity.DataBean>>()
    val groupBy = al.groupBy(SearchOptionPanelEntity.DataBean::getOrderid);
    groupBy.keys.forEach {
        val get = groupBy.get(it);
        val addAll = asb.add(get as java.util.ArrayList<SearchOptionPanelEntity.DataBean>)
    }
    return asb;
}

/**
 * 域名分组,企业中可能一个系统有多个服务器
 */
public fun groupDomain(data: List<CompanyDomainEntity.DataBean>): Map<String?, List<CompanyDomainEntity.DataBean>> {
    return data.groupBy { it.configuration_id }
}



