package com.suxuantech.erpsys.nohttp.ext;

import android.support.annotation.NonNull;

import com.alibaba.fastjson.JSON;
import com.yanzhenjie.nohttp.Headers;
import com.yanzhenjie.nohttp.RequestMethod;
import com.yanzhenjie.nohttp.rest.Request;
import com.yanzhenjie.nohttp.tools.MultiValueMap;

/**
 * ......................我佛慈悲....................
 * ......................_oo0oo_.....................
 * .....................o8888888o....................
 * .....................88" . "88....................
 * .....................(| -_- |)....................
 * .....................0\  =  /0....................
 * ...................___/`---'\___..................
 * ..................' \\|     |// '.................
 * ................./ \\|||  :  |||// \..............
 * .............../ _||||| -卍-|||||- \..............
 * ..............|   | \\\  -  /// |   |.............
 * ..............| \_|  ''\---/''  |_/ |.............
 * ..............\  .-\__  '-'  ___/-. /.............
 * ............___'. .'  /--.--\  `. .'___...........
 * .........."" '<  `.___\_<|>_/___.' >' ""..........
 * ........| | :  `- \`.;`\ _ /`;.`/ - ` : | |.......
 * ........\  \ `_.   \_ __\ /__ _/   .-` /  /.......
 * ....=====`-.____`.___ \_____/___.-`___.-'=====....
 * ......................`=---='.....................
 * ..................佛祖开光 ,永无BUG................
 *
 * @author Created by 李站旗 on 2018/3/9 0009 15:06 .
 *         QQ:1032992210
 *         E-mail:lizhanqihd@163.com
 * @Description: todo(用一句话描述该文件做什么)
 */

public class BaseRequest extends Request {
    public BaseRequest(String url) {
        super(url);
    }

    public BaseRequest(String url, RequestMethod requestMethod) {
        super(url, requestMethod);
    }
    @Override
    public Object parseResponse(Headers responseHeaders, byte[] responseBody) throws Exception {
        return null;
    }

    @Override
    public int compareTo(@NonNull Object o) {

        return 0;
    }
    public void  Param2Json(){
        MultiValueMap paramKeyValues = getParamKeyValues();
        addHeader("Content-Type", "application/json");
        setDefineRequestBodyForJson(JSON.toJSONString(paramKeyValues));
    }

}
